### ISSUE TITLE
ACF Reliability

### ISSUE THREAD

**Issue by bhardie** [wp-graphql/wp-graphql-acf#308]
- [ ] Create generic ACF field group gql interface type
- [ ] Each ACF field group should register a graphql object type that implements the gql interface
- [ ] Each ACF field group should be able to choose where in the gql schema it should show
- [ ] Each field in an ACF field group should be added to the schema under that group's gql object type
- [ ] Add support for ACF cloned field groups in WPGraphQL
- [ ]

**Comment by jasonbahl** [comment]
Closing as this was kind of an initial roadmap for the rewrite over at https://github.com/wp-graphql/wpgraphql-acf
